# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/Jenks/maya/scripts/Jenks/scripts/magicalRenamer/magicalRenamerUI.ui'
#
# Created: Sat Oct 14 18:45:26 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 150)
        MainWindow.setMinimumSize(QtCore.QSize(400, 160))
        MainWindow.setMaximumSize(QtCore.QSize(400, 160))
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.main_Grp = QtWidgets.QGroupBox(MainWindow)
        self.main_Grp.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.main_Grp.setTitle("")
        self.main_Grp.setObjectName("main_Grp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_Grp)
        self.gridLayout_3.setContentsMargins(4, 2, 4, 2)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainGrid_Lay = QtWidgets.QGridLayout()
        self.mainGrid_Lay.setHorizontalSpacing(5)
        self.mainGrid_Lay.setVerticalSpacing(4)
        self.mainGrid_Lay.setObjectName("mainGrid_Lay")
        self.rename_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.rename_Ledit.setMinimumSize(QtCore.QSize(0, 25))
        self.rename_Ledit.setObjectName("rename_Ledit")
        self.mainGrid_Lay.addWidget(self.rename_Ledit, 1, 1, 1, 2)
        self.replace_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.replace_Ledit.setMinimumSize(QtCore.QSize(300, 25))
        self.replace_Ledit.setObjectName("replace_Ledit")
        self.mainGrid_Lay.addWidget(self.replace_Ledit, 5, 0, 1, 3)
        self.side_Cbox = QtWidgets.QComboBox(self.main_Grp)
        self.side_Cbox.setMaximumSize(QtCore.QSize(45, 16777215))
        self.side_Cbox.setObjectName("side_Cbox")
        self.side_Cbox.addItem("")
        self.side_Cbox.addItem("")
        self.side_Cbox.addItem("")
        self.mainGrid_Lay.addWidget(self.side_Cbox, 1, 0, 1, 1)
        self.top_Line = QtWidgets.QFrame(self.main_Grp)
        self.top_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.top_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top_Line.setObjectName("top_Line")
        self.mainGrid_Lay.addWidget(self.top_Line, 3, 0, 1, 4)
        self.replace_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_Btn.sizePolicy().hasHeightForWidth())
        self.replace_Btn.setSizePolicy(sizePolicy)
        self.replace_Btn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.replace_Btn.setObjectName("replace_Btn")
        self.mainGrid_Lay.addWidget(self.replace_Btn, 4, 3, 2, 1)
        self.find_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.find_Ledit.setMinimumSize(QtCore.QSize(300, 25))
        self.find_Ledit.setObjectName("find_Ledit")
        self.mainGrid_Lay.addWidget(self.find_Ledit, 4, 0, 1, 3)
        self.mid_Line = QtWidgets.QFrame(self.main_Grp)
        self.mid_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.mid_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mid_Line.setObjectName("mid_Line")
        self.mainGrid_Lay.addWidget(self.mid_Line, 6, 0, 1, 4)
        self.rename_Btn = QtWidgets.QPushButton(self.main_Grp)
        self.rename_Btn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.rename_Btn.setDefault(False)
        self.rename_Btn.setObjectName("rename_Btn")
        self.mainGrid_Lay.addWidget(self.rename_Btn, 1, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clear_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_Btn.sizePolicy().hasHeightForWidth())
        self.clear_Btn.setSizePolicy(sizePolicy)
        self.clear_Btn.setMinimumSize(QtCore.QSize(35, 20))
        self.clear_Btn.setMaximumSize(QtCore.QSize(25, 20))
        self.clear_Btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear_Btn.setObjectName("clear_Btn")
        self.gridLayout_2.addWidget(self.clear_Btn, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.mainGrid_Lay.addLayout(self.gridLayout_2, 0, 3, 1, 1)
        self.mini_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mini_Btn.sizePolicy().hasHeightForWidth())
        self.mini_Btn.setSizePolicy(sizePolicy)
        self.mini_Btn.setMinimumSize(QtCore.QSize(0, 0))
        self.mini_Btn.setMaximumSize(QtCore.QSize(15, 15))
        self.mini_Btn.setObjectName("mini_Btn")
        self.mainGrid_Lay.addWidget(self.mini_Btn, 0, 0, 1, 1)
        self.radio_Grp = QtWidgets.QWidget(self.main_Grp)
        self.radio_Grp.setMaximumSize(QtCore.QSize(500, 30))
        self.radio_Grp.setObjectName("radio_Grp")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.radio_Grp)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.heirachy_Rad = QtWidgets.QRadioButton(self.radio_Grp)
        self.heirachy_Rad.setMaximumSize(QtCore.QSize(75, 16777215))
        self.heirachy_Rad.setObjectName("heirachy_Rad")
        self.gridLayout_6.addWidget(self.heirachy_Rad, 1, 2, 1, 1)
        self.selected_Rad = QtWidgets.QRadioButton(self.radio_Grp)
        self.selected_Rad.setMaximumSize(QtCore.QSize(75, 16777215))
        self.selected_Rad.setChecked(True)
        self.selected_Rad.setObjectName("selected_Rad")
        self.gridLayout_6.addWidget(self.selected_Rad, 1, 1, 1, 1)
        self.mainGrid_Lay.addWidget(self.radio_Grp, 0, 1, 1, 2)
        self.gridLayout_3.addLayout(self.mainGrid_Lay, 0, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(5, -1, -1, 0)
        self.gridLayout_4.setHorizontalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stripR_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stripR_Btn.sizePolicy().hasHeightForWidth())
        self.stripR_Btn.setSizePolicy(sizePolicy)
        self.stripR_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.stripR_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.stripR_Btn.setObjectName("stripR_Btn")
        self.gridLayout_4.addWidget(self.stripR_Btn, 0, 11, 1, 1)
        self.stripL_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stripL_Btn.sizePolicy().hasHeightForWidth())
        self.stripL_Btn.setSizePolicy(sizePolicy)
        self.stripL_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.stripL_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.stripL_Btn.setObjectName("stripL_Btn")
        self.gridLayout_4.addWidget(self.stripL_Btn, 0, 8, 1, 1)
        self.line = QtWidgets.QFrame(self.main_Grp)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 7, 1, 1)
        self.suffix_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suffix_Btn.sizePolicy().hasHeightForWidth())
        self.suffix_Btn.setSizePolicy(sizePolicy)
        self.suffix_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.suffix_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.suffix_Btn.setObjectName("suffix_Btn")
        self.gridLayout_4.addWidget(self.suffix_Btn, 0, 6, 1, 1)
        self.prefix_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefix_Btn.sizePolicy().hasHeightForWidth())
        self.prefix_Btn.setSizePolicy(sizePolicy)
        self.prefix_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.prefix_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.prefix_Btn.setObjectName("prefix_Btn")
        self.gridLayout_4.addWidget(self.prefix_Btn, 0, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.main_Grp)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.main_Grp, 2, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.replace_Ledit, QtCore.SIGNAL("returnPressed()"), self.replace_Btn.animateClick)
        QtCore.QObject.connect(self.find_Ledit, QtCore.SIGNAL("returnPressed()"), self.replace_Btn.animateClick)
        QtCore.QObject.connect(self.rename_Ledit, QtCore.SIGNAL("returnPressed()"), self.rename_Btn.animateClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.selected_Rad, self.heirachy_Rad)
        MainWindow.setTabOrder(self.heirachy_Rad, self.side_Cbox)
        MainWindow.setTabOrder(self.side_Cbox, self.rename_Ledit)
        MainWindow.setTabOrder(self.rename_Ledit, self.find_Ledit)
        MainWindow.setTabOrder(self.find_Ledit, self.replace_Ledit)
        MainWindow.setTabOrder(self.replace_Ledit, self.rename_Btn)
        MainWindow.setTabOrder(self.rename_Btn, self.replace_Btn)
        MainWindow.setTabOrder(self.replace_Btn, self.prefix_Btn)
        MainWindow.setTabOrder(self.prefix_Btn, self.suffix_Btn)
        MainWindow.setTabOrder(self.suffix_Btn, self.stripL_Btn)
        MainWindow.setTabOrder(self.stripL_Btn, self.stripR_Btn)
        MainWindow.setTabOrder(self.stripR_Btn, self.clear_Btn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Jenks\' Magical Renamer", None, -1))
        self.rename_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Rename", None, -1))
        self.replace_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Replace", None, -1))
        self.side_Cbox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.side_Cbox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "L", None, -1))
        self.side_Cbox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "R", None, -1))
        self.replace_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Replace", None, -1))
        self.find_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Find", None, -1))
        self.rename_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Rename", None, -1))
        self.clear_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.mini_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "^", None, -1))
        self.heirachy_Rad.setText(QtWidgets.QApplication.translate("MainWindow", "Hierachy", None, -1))
        self.selected_Rad.setText(QtWidgets.QApplication.translate("MainWindow", "Selected", None, -1))
        self.stripR_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Strip R", None, -1))
        self.stripL_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Strip L", None, -1))
        self.suffix_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Suffix", None, -1))
        self.prefix_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Prefix", None, -1))

