# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/Jenks/maya/scripts/Jenks/scripts/magicalRenamer/renamerUI.ui'
#
# Created: Tue Nov 22 00:24:44 2016
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

try:
    from PySide import QtGui, QtCore
    import PySide.QtGui as QtWidgets
except ImportError:
    from PySide2 import QtGui, QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 214)
        MainWindow.setMinimumSize(QtCore.QSize(444, 214))
        MainWindow.setMaximumSize(QtCore.QSize(444, 214))
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.main_Grp = QtWidgets.QGroupBox(MainWindow)
        self.main_Grp.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.main_Grp.setTitle("")
        self.main_Grp.setObjectName("main_Grp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_Grp)
        self.gridLayout_3.setContentsMargins(4, 2, 4, 2)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lowBtnGrid_Lay = QtWidgets.QGridLayout()
        self.lowBtnGrid_Lay.setContentsMargins(0, -1, -1, -1)
        self.lowBtnGrid_Lay.setHorizontalSpacing(5)
        self.lowBtnGrid_Lay.setVerticalSpacing(7)
        self.lowBtnGrid_Lay.setObjectName("lowBtnGrid_Lay")
        self.eff_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eff_Btn.sizePolicy().hasHeightForWidth())
        self.eff_Btn.setSizePolicy(sizePolicy)
        self.eff_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.eff_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.eff_Btn.setObjectName("eff_Btn")
        self.lowBtnGrid_Lay.addWidget(self.eff_Btn, 1, 0, 1, 1)
        self.lowBtnVert_Line_2 = QtWidgets.QFrame(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowBtnVert_Line_2.sizePolicy().hasHeightForWidth())
        self.lowBtnVert_Line_2.setSizePolicy(sizePolicy)
        self.lowBtnVert_Line_2.setMinimumSize(QtCore.QSize(2, 0))
        self.lowBtnVert_Line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.lowBtnVert_Line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lowBtnVert_Line_2.setObjectName("lowBtnVert_Line_2")
        self.lowBtnGrid_Lay.addWidget(self.lowBtnVert_Line_2, 0, 5, 2, 1)
        self.geo_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geo_Btn.sizePolicy().hasHeightForWidth())
        self.geo_Btn.setSizePolicy(sizePolicy)
        self.geo_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.geo_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.geo_Btn.setObjectName("geo_Btn")
        self.lowBtnGrid_Lay.addWidget(self.geo_Btn, 0, 2, 1, 1)
        self.lowBtnVert_Line = QtWidgets.QFrame(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowBtnVert_Line.sizePolicy().hasHeightForWidth())
        self.lowBtnVert_Line.setSizePolicy(sizePolicy)
        self.lowBtnVert_Line.setMinimumSize(QtCore.QSize(2, 0))
        self.lowBtnVert_Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.lowBtnVert_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lowBtnVert_Line.setObjectName("lowBtnVert_Line")
        self.lowBtnGrid_Lay.addWidget(self.lowBtnVert_Line, 0, 8, 2, 1)
        self.L2R_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L2R_Btn.sizePolicy().hasHeightForWidth())
        self.L2R_Btn.setSizePolicy(sizePolicy)
        self.L2R_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.L2R_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.L2R_Btn.setObjectName("L2R_Btn")
        self.lowBtnGrid_Lay.addWidget(self.L2R_Btn, 0, 9, 1, 1)
        self.jnt_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jnt_Btn.sizePolicy().hasHeightForWidth())
        self.jnt_Btn.setSizePolicy(sizePolicy)
        self.jnt_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.jnt_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.jnt_Btn.setObjectName("jnt_Btn")
        self.lowBtnGrid_Lay.addWidget(self.jnt_Btn, 1, 3, 1, 1)
        self.prefixL_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefixL_Btn.sizePolicy().hasHeightForWidth())
        self.prefixL_Btn.setSizePolicy(sizePolicy)
        self.prefixL_Btn.setMinimumSize(QtCore.QSize(25, 25))
        self.prefixL_Btn.setObjectName("prefixL_Btn")
        self.lowBtnGrid_Lay.addWidget(self.prefixL_Btn, 0, 6, 1, 1)
        self.R2L_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2L_Btn.sizePolicy().hasHeightForWidth())
        self.R2L_Btn.setSizePolicy(sizePolicy)
        self.R2L_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.R2L_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.R2L_Btn.setObjectName("R2L_Btn")
        self.lowBtnGrid_Lay.addWidget(self.R2L_Btn, 1, 9, 1, 1)
        self.stripL_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stripL_Btn.sizePolicy().hasHeightForWidth())
        self.stripL_Btn.setSizePolicy(sizePolicy)
        self.stripL_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.stripL_Btn.setObjectName("stripL_Btn")
        self.lowBtnGrid_Lay.addWidget(self.stripL_Btn, 0, 11, 1, 1)
        self.hdl_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hdl_Btn.sizePolicy().hasHeightForWidth())
        self.hdl_Btn.setSizePolicy(sizePolicy)
        self.hdl_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.hdl_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.hdl_Btn.setObjectName("hdl_Btn")
        self.lowBtnGrid_Lay.addWidget(self.hdl_Btn, 1, 1, 1, 1)
        self.grp_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_Btn.sizePolicy().hasHeightForWidth())
        self.grp_Btn.setSizePolicy(sizePolicy)
        self.grp_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.grp_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.grp_Btn.setObjectName("grp_Btn")
        self.lowBtnGrid_Lay.addWidget(self.grp_Btn, 0, 1, 1, 1)
        self.loc_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loc_Btn.sizePolicy().hasHeightForWidth())
        self.loc_Btn.setSizePolicy(sizePolicy)
        self.loc_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.loc_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.loc_Btn.setObjectName("loc_Btn")
        self.lowBtnGrid_Lay.addWidget(self.loc_Btn, 0, 0, 1, 1)
        self.lowBtnVert_Line_3 = QtWidgets.QFrame(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowBtnVert_Line_3.sizePolicy().hasHeightForWidth())
        self.lowBtnVert_Line_3.setSizePolicy(sizePolicy)
        self.lowBtnVert_Line_3.setMinimumSize(QtCore.QSize(2, 0))
        self.lowBtnVert_Line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.lowBtnVert_Line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lowBtnVert_Line_3.setObjectName("lowBtnVert_Line_3")
        self.lowBtnGrid_Lay.addWidget(self.lowBtnVert_Line_3, 0, 10, 2, 1)
        self.ctrl_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_Btn.sizePolicy().hasHeightForWidth())
        self.ctrl_Btn.setSizePolicy(sizePolicy)
        self.ctrl_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.ctrl_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.ctrl_Btn.setObjectName("ctrl_Btn")
        self.lowBtnGrid_Lay.addWidget(self.ctrl_Btn, 1, 2, 1, 1)
        self.prefixR_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefixR_Btn.sizePolicy().hasHeightForWidth())
        self.prefixR_Btn.setSizePolicy(sizePolicy)
        self.prefixR_Btn.setMinimumSize(QtCore.QSize(25, 25))
        self.prefixR_Btn.setObjectName("prefixR_Btn")
        self.lowBtnGrid_Lay.addWidget(self.prefixR_Btn, 1, 6, 1, 1)
        self.bind_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bind_Btn.sizePolicy().hasHeightForWidth())
        self.bind_Btn.setSizePolicy(sizePolicy)
        self.bind_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.bind_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.bind_Btn.setObjectName("bind_Btn")
        self.lowBtnGrid_Lay.addWidget(self.bind_Btn, 0, 3, 1, 1)
        self.stripR_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stripR_Btn.sizePolicy().hasHeightForWidth())
        self.stripR_Btn.setSizePolicy(sizePolicy)
        self.stripR_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.stripR_Btn.setObjectName("stripR_Btn")
        self.lowBtnGrid_Lay.addWidget(self.stripR_Btn, 1, 11, 1, 1)
        self.replaceFix_Chk = QtWidgets.QCheckBox(self.main_Grp)
        self.replaceFix_Chk.setChecked(False)
        self.replaceFix_Chk.setObjectName("replaceFix_Chk")
        self.lowBtnGrid_Lay.addWidget(self.replaceFix_Chk, 0, 4, 1, 1)
        self.crv_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crv_Btn.sizePolicy().hasHeightForWidth())
        self.crv_Btn.setSizePolicy(sizePolicy)
        self.crv_Btn.setMinimumSize(QtCore.QSize(50, 25))
        self.crv_Btn.setMaximumSize(QtCore.QSize(75, 25))
        self.crv_Btn.setObjectName("crv_Btn")
        self.lowBtnGrid_Lay.addWidget(self.crv_Btn, 1, 4, 1, 1)
        self.gridLayout_3.addLayout(self.lowBtnGrid_Lay, 3, 0, 1, 1)
        self.mainGrid_Lay = QtWidgets.QGridLayout()
        self.mainGrid_Lay.setHorizontalSpacing(18)
        self.mainGrid_Lay.setVerticalSpacing(4)
        self.mainGrid_Lay.setObjectName("mainGrid_Lay")
        self.rename_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.rename_Ledit.setMinimumSize(QtCore.QSize(300, 0))
        self.rename_Ledit.setObjectName("rename_Ledit")
        self.mainGrid_Lay.addWidget(self.rename_Ledit, 1, 0, 1, 3)
        self.suffix_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.suffix_Ledit.setText("")
        self.suffix_Ledit.setObjectName("suffix_Ledit")
        self.mainGrid_Lay.addWidget(self.suffix_Ledit, 6, 2, 1, 1)
        self.find_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.find_Ledit.setMinimumSize(QtCore.QSize(300, 0))
        self.find_Ledit.setObjectName("find_Ledit")
        self.mainGrid_Lay.addWidget(self.find_Ledit, 3, 0, 1, 3)
        self.prefix_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.prefix_Ledit.setText("")
        self.prefix_Ledit.setObjectName("prefix_Ledit")
        self.mainGrid_Lay.addWidget(self.prefix_Ledit, 6, 0, 1, 1)
        self.replace_Ledit = QtWidgets.QLineEdit(self.main_Grp)
        self.replace_Ledit.setMinimumSize(QtCore.QSize(300, 0))
        self.replace_Ledit.setObjectName("replace_Ledit")
        self.mainGrid_Lay.addWidget(self.replace_Ledit, 4, 0, 1, 3)
        self.prefix_Btn = QtWidgets.QPushButton(self.main_Grp)
        self.prefix_Btn.setObjectName("prefix_Btn")
        self.mainGrid_Lay.addWidget(self.prefix_Btn, 6, 1, 1, 1)
        self.radio_Grp = QtWidgets.QWidget(self.main_Grp)
        self.radio_Grp.setMaximumSize(QtCore.QSize(500, 30))
        self.radio_Grp.setObjectName("radio_Grp")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.radio_Grp)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.heirachy_Rad = QtWidgets.QRadioButton(self.radio_Grp)
        self.heirachy_Rad.setMaximumSize(QtCore.QSize(75, 16777215))
        self.heirachy_Rad.setObjectName("heirachy_Rad")
        self.gridLayout_6.addWidget(self.heirachy_Rad, 1, 3, 1, 1)
        self.selected_Rad = QtWidgets.QRadioButton(self.radio_Grp)
        self.selected_Rad.setMaximumSize(QtCore.QSize(75, 16777215))
        self.selected_Rad.setChecked(True)
        self.selected_Rad.setObjectName("selected_Rad")
        self.gridLayout_6.addWidget(self.selected_Rad, 1, 2, 1, 1)
        self.all_Rad = QtWidgets.QRadioButton(self.radio_Grp)
        self.all_Rad.setMaximumSize(QtCore.QSize(50, 16777215))
        self.all_Rad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.all_Rad.setObjectName("all_Rad")
        self.gridLayout_6.addWidget(self.all_Rad, 1, 1, 1, 1)
        self.mainGrid_Lay.addWidget(self.radio_Grp, 0, 0, 1, 3)
        self.clear_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_Btn.sizePolicy().hasHeightForWidth())
        self.clear_Btn.setSizePolicy(sizePolicy)
        self.clear_Btn.setMinimumSize(QtCore.QSize(35, 20))
        self.clear_Btn.setMaximumSize(QtCore.QSize(25, 20))
        self.clear_Btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear_Btn.setObjectName("clear_Btn")
        self.mainGrid_Lay.addWidget(self.clear_Btn, 0, 4, 1, 1)
        self.rename_Btn = QtWidgets.QPushButton(self.main_Grp)
        self.rename_Btn.setDefault(False)
        self.rename_Btn.setObjectName("rename_Btn")
        self.mainGrid_Lay.addWidget(self.rename_Btn, 1, 3, 1, 2)
        self.replace_Btn = QtWidgets.QPushButton(self.main_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_Btn.sizePolicy().hasHeightForWidth())
        self.replace_Btn.setSizePolicy(sizePolicy)
        self.replace_Btn.setObjectName("replace_Btn")
        self.mainGrid_Lay.addWidget(self.replace_Btn, 3, 3, 2, 2)
        self.suffix_Btn = QtWidgets.QPushButton(self.main_Grp)
        self.suffix_Btn.setObjectName("suffix_Btn")
        self.mainGrid_Lay.addWidget(self.suffix_Btn, 6, 3, 1, 2)
        self.top_Line = QtWidgets.QFrame(self.main_Grp)
        self.top_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.top_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top_Line.setObjectName("top_Line")
        self.mainGrid_Lay.addWidget(self.top_Line, 2, 0, 1, 5)
        self.mid_Line = QtWidgets.QFrame(self.main_Grp)
        self.mid_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.mid_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mid_Line.setObjectName("mid_Line")
        self.mainGrid_Lay.addWidget(self.mid_Line, 5, 0, 1, 5)
        self.low_Line = QtWidgets.QFrame(self.main_Grp)
        self.low_Line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.low_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.low_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.low_Line.setObjectName("low_Line")
        self.mainGrid_Lay.addWidget(self.low_Line, 7, 0, 1, 5)
        self.gridLayout_3.addLayout(self.mainGrid_Lay, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.main_Grp, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.find_Ledit, QtCore.SIGNAL("returnPressed()"), self.replace_Btn.animateClick)
        QtCore.QObject.connect(self.prefix_Ledit, QtCore.SIGNAL("returnPressed()"), self.prefix_Btn.animateClick)
        QtCore.QObject.connect(self.rename_Ledit, QtCore.SIGNAL("returnPressed()"), self.rename_Btn.animateClick)
        QtCore.QObject.connect(self.suffix_Ledit, QtCore.SIGNAL("returnPressed()"), self.suffix_Btn.animateClick)
        QtCore.QObject.connect(self.replace_Ledit, QtCore.SIGNAL("returnPressed()"), self.replace_Btn.animateClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Jenks\' Magical Renamer", None, -1))
        self.eff_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_EFF", None, -1))
        self.geo_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_GEO", None, -1))
        self.L2R_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "L -> R", None, -1))
        self.jnt_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_JNT", None, -1))
        self.prefixL_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "L_", None, -1))
        self.R2L_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "R -> L", None, -1))
        self.stripL_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Strip L", None, -1))
        self.hdl_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_HDL", None, -1))
        self.grp_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_GRP", None, -1))
        self.loc_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_LOC", None, -1))
        self.ctrl_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_CTRL", None, -1))
        self.prefixR_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "R_", None, -1))
        self.bind_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_BIND", None, -1))
        self.stripR_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Strip R", None, -1))
        self.replaceFix_Chk.setText(QtWidgets.QApplication.translate("MainWindow", "R", None, -1))
        self.crv_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "_CRV", None, -1))
        self.rename_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Rename", None, -1))
        self.suffix_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "_Suffix", None, -1))
        self.find_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Find", None, -1))
        self.prefix_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Prefix_", None, -1))
        self.replace_Ledit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Replace", None, -1))
        self.prefix_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Prefix", None, -1))
        self.heirachy_Rad.setText(QtWidgets.QApplication.translate("MainWindow", "Hierachy", None, -1))
        self.selected_Rad.setText(QtWidgets.QApplication.translate("MainWindow", "Selected", None, -1))
        self.all_Rad.setText(QtWidgets.QApplication.translate("MainWindow", "All", None, -1))
        self.clear_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.rename_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Rename", None, -1))
        self.replace_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Replace", None, -1))
        self.suffix_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Suffix", None, -1))

