# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/Jenks/maya/scripts/Jenks/scripts/curveCreator/crvCreatorUI.ui'
#
# Created: Wed Sep 21 14:13:09 2016
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

import maya.cmds as cmds
from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        iconDir=cmds.internalVar(uad=True)+"scripts/Jenks/scripts/curveCreator/icons/"
        ###
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 535)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 336))
        MainWindow.setMaximumSize(QtCore.QSize(300, 700))
        self.gridLayout_6 = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mirrorHor_Lay = QtWidgets.QVBoxLayout()
        self.mirrorHor_Lay.setContentsMargins(5, 5, 5, 5)
        self.mirrorHor_Lay.setObjectName("mirrorHor_Lay")
        self.mirror_Grp = QtWidgets.QGroupBox(MainWindow)
        self.mirror_Grp.setObjectName("mirror_Grp")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mirror_Grp)
        self.gridLayout_7.setContentsMargins(40, 2, 40, 7)
        self.gridLayout_7.setHorizontalSpacing(20)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.x_Btn = QtWidgets.QPushButton(self.mirror_Grp)
        self.x_Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.x_Btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.x_Btn.setObjectName("x_Btn")
        self.gridLayout_7.addWidget(self.x_Btn, 0, 0, 1, 1)
        self.y_Btn = QtWidgets.QPushButton(self.mirror_Grp)
        self.y_Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.y_Btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.y_Btn.setObjectName("y_Btn")
        self.gridLayout_7.addWidget(self.y_Btn, 0, 1, 1, 1)
        self.z_Btn = QtWidgets.QPushButton(self.mirror_Grp)
        self.z_Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.z_Btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.z_Btn.setObjectName("z_Btn")
        self.gridLayout_7.addWidget(self.z_Btn, 0, 2, 1, 1)
        self.mirrorHor_Lay.addWidget(self.mirror_Grp)
        self.gridLayout_6.addLayout(self.mirrorHor_Lay, 6, 0, 1, 2)
        self.line01_Line = QtWidgets.QFrame(MainWindow)
        self.line01_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line01_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line01_Line.setObjectName("line01_Line")
        self.gridLayout_6.addWidget(self.line01_Line, 5, 0, 1, 2)
        self.freeze_Btn = QtWidgets.QPushButton(MainWindow)
        self.freeze_Btn.setObjectName("freeze_Btn")
        self.gridLayout_6.addWidget(self.freeze_Btn, 7, 1, 1, 1)
        self.colourHor_Lay = QtWidgets.QVBoxLayout()
        self.colourHor_Lay.setContentsMargins(5, 5, 5, 5)
        self.colourHor_Lay.setObjectName("colourHor_Lay")
        self.colour_Grp = QtWidgets.QGroupBox(MainWindow)
        self.colour_Grp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.colour_Grp.setCheckable(False)
        self.colour_Grp.setObjectName("colour_Grp")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.colour_Grp)
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setContentsMargins(15, 5, 10, 2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lowBtnVert_Lay = QtWidgets.QHBoxLayout()
        self.lowBtnVert_Lay.setObjectName("lowBtnVert_Lay")
        self.default_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.default_Btn.setMinimumSize(QtCore.QSize(0, 20))
        self.default_Btn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.default_Btn.setObjectName("default_Btn")
        self.lowBtnVert_Lay.addWidget(self.default_Btn)
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lowBtnVert_Lay.addItem(spacerItem)
        self.override_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.override_Btn.setMinimumSize(QtCore.QSize(0, 20))
        self.override_Btn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.override_Btn.setObjectName("override_Btn")
        self.lowBtnVert_Lay.addWidget(self.override_Btn)
        self.gridLayout_5.addLayout(self.lowBtnVert_Lay, 3, 2, 1, 9)
        self.colour10_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour10_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour10_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour10_Btn.setText("")
        self.colour10_Btn.setCheckable(True)
        self.colour10_Btn.setAutoExclusive(True)
        self.colour10_Btn.setObjectName("colour10_Btn")
        self.colour10_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour10.png')))
        self.colour10_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour10_Btn, 0, 10, 1, 1)
        self.colour12_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour12_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour12_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour12_Btn.setText("")
        self.colour12_Btn.setCheckable(True)
        self.colour12_Btn.setAutoExclusive(True)
        self.colour12_Btn.setObjectName("colour12_Btn")
        self.colour12_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour12.png')))
        self.colour12_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour12_Btn, 1, 1, 1, 1)
        self.colour21_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour21_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour21_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour21_Btn.setText("")
        self.colour21_Btn.setCheckable(True)
        self.colour21_Btn.setAutoExclusive(True)
        self.colour21_Btn.setObjectName("colour21_Btn")
        self.colour21_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour21.png')))
        self.colour21_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour21_Btn, 1, 10, 1, 1)
        self.colour23_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour23_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour23_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour23_Btn.setText("")
        self.colour23_Btn.setCheckable(True)
        self.colour23_Btn.setAutoExclusive(True)
        self.colour23_Btn.setObjectName("colour23_Btn")
        self.colour23_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour23.png')))
        self.colour23_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour23_Btn, 2, 1, 1, 1)
        self.colour28_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour28_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour28_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour28_Btn.setText("")
        self.colour28_Btn.setCheckable(True)
        self.colour28_Btn.setAutoExclusive(True)
        self.colour28_Btn.setObjectName("colour28_Btn")
        self.colour28_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour28.png')))
        self.colour28_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour28_Btn, 2, 6, 1, 1)
        self.colour14_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour14_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour14_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour14_Btn.setText("")
        self.colour14_Btn.setCheckable(True)
        self.colour14_Btn.setAutoExclusive(True)
        self.colour14_Btn.setObjectName("colour14_Btn")
        self.colour14_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour14.png')))
        self.colour14_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour14_Btn, 1, 3, 1, 1)
        self.colour17_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour17_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour17_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour17_Btn.setText("")
        self.colour17_Btn.setCheckable(True)
        self.colour17_Btn.setAutoExclusive(True)
        self.colour17_Btn.setObjectName("colour17_Btn")
        self.colour17_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour17.png')))
        self.colour17_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour17_Btn, 1, 6, 1, 1)
        self.colour24_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour24_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour24_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour24_Btn.setText("")
        self.colour24_Btn.setCheckable(True)
        self.colour24_Btn.setAutoExclusive(True)
        self.colour24_Btn.setObjectName("colour24_Btn")
        self.colour24_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour24.png')))
        self.colour24_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour24_Btn, 2, 2, 1, 1)
        self.colour13_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour13_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour13_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour13_Btn.setText("")
        self.colour13_Btn.setCheckable(True)
        self.colour13_Btn.setAutoExclusive(True)
        self.colour13_Btn.setObjectName("colour13_Btn")
        self.colour13_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour13.png')))
        self.colour13_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour13_Btn, 1, 2, 1, 1)
        self.colour26_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour26_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour26_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour26_Btn.setText("")
        self.colour26_Btn.setCheckable(True)
        self.colour26_Btn.setAutoExclusive(True)
        self.colour26_Btn.setObjectName("colour26_Btn")
        self.colour26_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour26.png')))
        self.colour26_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour26_Btn, 2, 4, 1, 1)
        self.colour31_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour31_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour31_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour31_Btn.setText("")
        self.colour31_Btn.setCheckable(True)
        self.colour31_Btn.setAutoExclusive(True)
        self.colour31_Btn.setObjectName("colour31_Btn")
        self.colour31_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour31.png')))
        self.colour31_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour31_Btn, 2, 9, 1, 1)
        self.colour30_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour30_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour30_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour30_Btn.setText("")
        self.colour30_Btn.setCheckable(True)
        self.colour30_Btn.setAutoExclusive(True)
        self.colour30_Btn.setObjectName("colour30_Btn")
        self.colour30_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour30.png')))
        self.colour30_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour30_Btn, 2, 8, 1, 1)
        self.colour19_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour19_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour19_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour19_Btn.setText("")
        self.colour19_Btn.setCheckable(True)
        self.colour19_Btn.setAutoExclusive(True)
        self.colour19_Btn.setObjectName("colour19_Btn")
        self.colour19_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour19.png')))
        self.colour19_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour19_Btn, 1, 8, 1, 1)
        self.colour20_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour20_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour20_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour20_Btn.setText("")
        self.colour20_Btn.setCheckable(True)
        self.colour20_Btn.setAutoExclusive(True)
        self.colour20_Btn.setObjectName("colour20_Btn")
        self.colour20_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour20.png')))
        self.colour20_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour20_Btn, 1, 9, 1, 1)
        self.colour01_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour01_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour01_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour01_Btn.setText("")
        self.colour01_Btn.setCheckable(True)
        self.colour01_Btn.setChecked(True)
        self.colour01_Btn.setAutoExclusive(True)
        self.colour01_Btn.setObjectName("colour01_Btn")
        self.colour01_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour01.png')))
        self.colour01_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour01_Btn, 0, 1, 1, 1)
        self.colour22_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour22_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour22_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour22_Btn.setText("")
        self.colour22_Btn.setCheckable(True)
        self.colour22_Btn.setAutoExclusive(True)
        self.colour22_Btn.setObjectName("colour22_Btn")
        self.colour22_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour22.png')))
        self.colour22_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour22_Btn, 1, 11, 1, 1)
        self.colour06_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour06_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour06_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour06_Btn.setText("")
        self.colour06_Btn.setCheckable(True)
        self.colour06_Btn.setAutoExclusive(True)
        self.colour06_Btn.setObjectName("colour06_Btn")
        self.colour06_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour06.png')))
        self.colour06_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour06_Btn, 0, 6, 1, 1)
        self.colour25_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour25_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour25_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour25_Btn.setText("")
        self.colour25_Btn.setCheckable(True)
        self.colour25_Btn.setAutoExclusive(True)
        self.colour25_Btn.setObjectName("colour25_Btn")
        self.colour25_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour25.png')))
        self.colour25_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour25_Btn, 2, 3, 1, 1)
        self.colour27_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour27_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour27_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour27_Btn.setText("")
        self.colour27_Btn.setCheckable(True)
        self.colour27_Btn.setAutoExclusive(True)
        self.colour27_Btn.setObjectName("colour27_Btn")
        self.colour27_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour27.png')))
        self.colour27_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour27_Btn, 2, 5, 1, 1)
        self.colour02_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour02_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour02_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour02_Btn.setText("")
        self.colour02_Btn.setCheckable(True)
        self.colour02_Btn.setAutoExclusive(True)
        self.colour02_Btn.setObjectName("colour02_Btn")
        self.colour02_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour02.png')))
        self.colour02_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour02_Btn, 0, 2, 1, 1)
        self.colour15_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour15_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour15_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour15_Btn.setText("")
        self.colour15_Btn.setCheckable(True)
        self.colour15_Btn.setAutoExclusive(True)
        self.colour15_Btn.setObjectName("colour15_Btn")
        self.colour15_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour15.png')))
        self.colour15_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour15_Btn, 1, 4, 1, 1)
        self.colour05_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour05_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour05_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour05_Btn.setText("")
        self.colour05_Btn.setCheckable(True)
        self.colour05_Btn.setAutoExclusive(True)
        self.colour05_Btn.setObjectName("colour05_Btn")
        self.colour05_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour05.png')))
        self.colour05_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour05_Btn, 0, 5, 1, 1)
        self.colour03_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour03_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour03_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour03_Btn.setText("")
        self.colour03_Btn.setCheckable(True)
        self.colour03_Btn.setAutoExclusive(True)
        self.colour03_Btn.setObjectName("colour03_Btn")
        self.colour03_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour03.png')))
        self.colour03_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour03_Btn, 0, 3, 1, 1)
        self.colour04_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour04_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour04_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour04_Btn.setText("")
        self.colour04_Btn.setCheckable(True)
        self.colour04_Btn.setAutoExclusive(True)
        self.colour04_Btn.setObjectName("colour04_Btn")
        self.colour04_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour04.png')))
        self.colour04_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour04_Btn, 0, 4, 1, 1)
        self.colour16_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour16_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour16_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour16_Btn.setText("")
        self.colour16_Btn.setCheckable(True)
        self.colour16_Btn.setAutoExclusive(True)
        self.colour16_Btn.setObjectName("colour16_Btn")
        self.colour16_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour16.png')))
        self.colour16_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour16_Btn, 1, 5, 1, 1)
        self.colour29_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour29_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour29_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour29_Btn.setText("")
        self.colour29_Btn.setCheckable(True)
        self.colour29_Btn.setAutoExclusive(True)
        self.colour29_Btn.setObjectName("colour29_Btn")
        self.colour29_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour29.png')))
        self.colour29_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour29_Btn, 2, 7, 1, 1)
        self.colour18_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour18_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour18_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour18_Btn.setText("")
        self.colour18_Btn.setCheckable(True)
        self.colour18_Btn.setAutoExclusive(True)
        self.colour18_Btn.setObjectName("colour18_Btn")
        self.colour18_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour18.png')))
        self.colour18_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour18_Btn, 1, 7, 1, 1)
        self.colour07_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour07_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour07_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour07_Btn.setText("")
        self.colour07_Btn.setCheckable(True)
        self.colour07_Btn.setAutoExclusive(True)
        self.colour07_Btn.setObjectName("colour07_Btn")
        self.colour07_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour07.png')))
        self.colour07_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour07_Btn, 0, 7, 1, 1)
        self.colour08_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour08_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour08_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour08_Btn.setText("")
        self.colour08_Btn.setCheckable(True)
        self.colour08_Btn.setAutoExclusive(True)
        self.colour08_Btn.setObjectName("colour08_Btn")
        self.colour08_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour08.png')))
        self.colour08_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour08_Btn, 0, 8, 1, 1)
        self.colour09_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour09_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour09_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour09_Btn.setText("")
        self.colour09_Btn.setCheckable(True)
        self.colour09_Btn.setAutoExclusive(True)
        self.colour09_Btn.setObjectName("colour09_Btn")
        self.colour09_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour09.png')))
        self.colour09_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour09_Btn, 0, 9, 1, 1)
        self.colour11_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour11_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour11_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour11_Btn.setText("")
        self.colour11_Btn.setCheckable(True)
        self.colour11_Btn.setAutoExclusive(True)
        self.colour11_Btn.setObjectName("colour11_Btn")
        self.colour11_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour11.png')))
        self.colour11_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour11_Btn, 0, 11, 1, 1)
        self.colour32_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour32_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour32_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour32_Btn.setText("")
        self.colour32_Btn.setCheckable(True)
        self.colour32_Btn.setAutoExclusive(True)
        self.colour32_Btn.setObjectName("colour32_Btn")
        self.colour32_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour32.png')))
        self.colour32_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour32_Btn, 2, 10, 1, 1)
        self.colour33_Btn = QtWidgets.QPushButton(self.colour_Grp)
        self.colour33_Btn.setMinimumSize(QtCore.QSize(20, 20))
        self.colour33_Btn.setMaximumSize(QtCore.QSize(20, 20))
        self.colour33_Btn.setText("")
        self.colour33_Btn.setCheckable(True)
        self.colour33_Btn.setAutoExclusive(True)
        self.colour33_Btn.setObjectName("colour33_Btn")
        #self.colour33_Btn.setIcon(QtGui.QIcon(str(iconDir+'Colour33.png')))
        #self.colour33_Btn.setIconSize(QtCore.QSize(16,16))
        self.gridLayout_5.addWidget(self.colour33_Btn, 2, 11, 1, 1)
        self.gridLayout_5.setRowMinimumHeight(3, 27)
        self.colourHor_Lay.addWidget(self.colour_Grp)
        self.gridLayout_6.addLayout(self.colourHor_Lay, 3, 0, 1, 2)
        self.bufferGrid_Lay = QtWidgets.QGridLayout()
        self.bufferGrid_Lay.setContentsMargins(15, 5, 15, 5)
        self.bufferGrid_Lay.setHorizontalSpacing(7)
        self.bufferGrid_Lay.setVerticalSpacing(10)
        self.bufferGrid_Lay.setObjectName("bufferGrid_Lay")
        self.name_Lab = QtWidgets.QLabel(MainWindow)
        self.name_Lab.setMinimumSize(QtCore.QSize(30, 0))
        self.name_Lab.setMaximumSize(QtCore.QSize(30, 16777215))
        self.name_Lab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_Lab.setObjectName("name_Lab")
        self.bufferGrid_Lay.addWidget(self.name_Lab, 0, 0, 1, 1)
        self.name_Ledit = QtWidgets.QLineEdit(MainWindow)
        self.name_Ledit.setObjectName("name_Ledit")
        self.bufferGrid_Lay.addWidget(self.name_Ledit, 0, 1, 1, 5)
        self.locNum_Cmb = QtWidgets.QComboBox(MainWindow)
        self.locNum_Cmb.setMinimumSize(QtCore.QSize(0, 0))
        self.locNum_Cmb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.locNum_Cmb.setObjectName("locNum_Cmb")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.locNum_Cmb.addItem("")
        self.bufferGrid_Lay.addWidget(self.locNum_Cmb, 1, 4, 1, 1)
        self.locators_Lab = QtWidgets.QLabel(MainWindow)
        self.locators_Lab.setMinimumSize(QtCore.QSize(45, 0))
        self.locators_Lab.setMaximumSize(QtCore.QSize(25, 16777215))
        self.locators_Lab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.locators_Lab.setObjectName("locators_Lab")
        self.bufferGrid_Lay.addWidget(self.locators_Lab, 1, 3, 1, 1)
        self.grpNum_Cmb = QtWidgets.QComboBox(MainWindow)
        self.grpNum_Cmb.setMinimumSize(QtCore.QSize(0, 0))
        self.grpNum_Cmb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.grpNum_Cmb.setObjectName("grpNum_Cmb")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.grpNum_Cmb.addItem("")
        self.bufferGrid_Lay.addWidget(self.grpNum_Cmb, 1, 2, 1, 1)
        self.groups_Lab = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groups_Lab.sizePolicy().hasHeightForWidth())
        self.groups_Lab.setSizePolicy(sizePolicy)
        self.groups_Lab.setMinimumSize(QtCore.QSize(40, 0))
        self.groups_Lab.setMaximumSize(QtCore.QSize(30, 16777215))
        self.groups_Lab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groups_Lab.setObjectName("groups_Lab")
        self.bufferGrid_Lay.addWidget(self.groups_Lab, 1, 1, 1, 1)
        self.create_Btn = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_Btn.sizePolicy().hasHeightForWidth())
        self.create_Btn.setSizePolicy(sizePolicy)
        self.create_Btn.setMinimumSize(QtCore.QSize(0, 35))
        self.create_Btn.setObjectName("create_Btn")
        self.bufferGrid_Lay.addWidget(self.create_Btn, 2, 0, 1, 6)
        self.gridLayout_6.addLayout(self.bufferGrid_Lay, 1, 0, 1, 2)
        self.topVert_Lay = QtWidgets.QVBoxLayout()
        self.topVert_Lay.setObjectName("topVert_Lay")
        self.shapes_Grp = QtWidgets.QGroupBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapes_Grp.sizePolicy().hasHeightForWidth())
        self.shapes_Grp.setSizePolicy(sizePolicy)
        self.shapes_Grp.setMinimumSize(QtCore.QSize(278, 148))
        self.shapes_Grp.setCheckable(True)
        self.shapes_Grp.setObjectName("shapes_Grp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.shapes_Grp)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.top_Scrl = QtWidgets.QScrollArea(self.shapes_Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_Scrl.sizePolicy().hasHeightForWidth())
        self.top_Scrl.setSizePolicy(sizePolicy)
        self.top_Scrl.setAutoFillBackground(False)
        self.top_Scrl.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.top_Scrl.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.top_Scrl.setWidgetResizable(True)
        self.top_Scrl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.top_Scrl.setObjectName("top_Scrl")
        self.topScrGrid_Lay = QtWidgets.QWidget()
        self.topScrGrid_Lay.setGeometry(QtCore.QRect(0, 0, 247, 288))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topScrGrid_Lay.sizePolicy().hasHeightForWidth())
        self.topScrGrid_Lay.setSizePolicy(sizePolicy)
        self.topScrGrid_Lay.setObjectName("topScrGrid_Lay")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.topScrGrid_Lay)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.shape25_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape25_Btn.sizePolicy().hasHeightForWidth())
        self.shape25_Btn.setSizePolicy(sizePolicy)
        self.shape25_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape25_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape25_Btn.setText("")
        self.shape25_Btn.setCheckable(True)
        self.shape25_Btn.setAutoExclusive(True)
        self.shape25_Btn.setObjectName("shape25_Btn")
        self.shape25_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape25.png')))
        self.shape25_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape25_Btn, 3, 5, 1, 1)
        self.shape42_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape42_Btn.sizePolicy().hasHeightForWidth())
        self.shape42_Btn.setSizePolicy(sizePolicy)
        self.shape42_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape42_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape42_Btn.setText("")
        self.shape42_Btn.setCheckable(True)
        self.shape42_Btn.setAutoExclusive(True)
        self.shape42_Btn.setObjectName("shape42_Btn")
        self.shape42_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape42.png')))
        self.shape42_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape42_Btn, 6, 4, 1, 1)
        self.shape41_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape41_Btn.sizePolicy().hasHeightForWidth())
        self.shape41_Btn.setSizePolicy(sizePolicy)
        self.shape41_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape41_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape41_Btn.setText("")
        self.shape41_Btn.setCheckable(True)
        self.shape41_Btn.setAutoExclusive(True)
        self.shape41_Btn.setObjectName("shape41_Btn")
        self.shape41_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape41.png')))
        self.shape41_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape41_Btn, 6, 3, 1, 1)
        self.shape39_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape39_Btn.sizePolicy().hasHeightForWidth())
        self.shape39_Btn.setSizePolicy(sizePolicy)
        self.shape39_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape39_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape39_Btn.setText("")
        self.shape39_Btn.setCheckable(True)
        self.shape39_Btn.setAutoExclusive(True)
        self.shape39_Btn.setObjectName("shape39_Btn")
        self.shape39_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape39.png')))
        self.shape39_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape39_Btn, 6, 1, 1, 1)
        self.shape36_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape36_Btn.sizePolicy().hasHeightForWidth())
        self.shape36_Btn.setSizePolicy(sizePolicy)
        self.shape36_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape36_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape36_Btn.setText("")
        self.shape36_Btn.setCheckable(True)
        self.shape36_Btn.setAutoExclusive(True)
        self.shape36_Btn.setObjectName("shape36_Btn")
        self.shape36_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape36.png')))
        self.shape36_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape36_Btn, 5, 4, 1, 1)
        self.shape35_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape35_Btn.sizePolicy().hasHeightForWidth())
        self.shape35_Btn.setSizePolicy(sizePolicy)
        self.shape35_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape35_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape35_Btn.setText("")
        self.shape35_Btn.setCheckable(True)
        self.shape35_Btn.setAutoExclusive(True)
        self.shape35_Btn.setObjectName("shape35_Btn")
        self.shape35_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape35.png')))
        self.shape35_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape35_Btn, 5, 3, 1, 1)
        self.shape30_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape30_Btn.sizePolicy().hasHeightForWidth())
        self.shape30_Btn.setSizePolicy(sizePolicy)
        self.shape30_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape30_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape30_Btn.setText("")
        self.shape30_Btn.setCheckable(True)
        self.shape30_Btn.setAutoExclusive(True)
        self.shape30_Btn.setObjectName("shape30_Btn")
        self.shape30_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape30.png')))
        self.shape30_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape30_Btn, 4, 4, 1, 1)
        self.shape29_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape29_Btn.sizePolicy().hasHeightForWidth())
        self.shape29_Btn.setSizePolicy(sizePolicy)
        self.shape29_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape29_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape29_Btn.setText("")
        self.shape29_Btn.setCheckable(True)
        self.shape29_Btn.setAutoExclusive(True)
        self.shape29_Btn.setObjectName("shape29_Btn")
        self.shape29_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape29.png')))
        self.shape29_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape29_Btn, 4, 3, 1, 1)
        self.shape24_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape24_Btn.sizePolicy().hasHeightForWidth())
        self.shape24_Btn.setSizePolicy(sizePolicy)
        self.shape24_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape24_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape24_Btn.setText("")
        self.shape24_Btn.setCheckable(True)
        self.shape24_Btn.setAutoExclusive(True)
        self.shape24_Btn.setObjectName("shape24_Btn")
        self.shape24_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape24.png')))
        self.shape24_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape24_Btn, 3, 4, 1, 1)
        self.shape23_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape23_Btn.sizePolicy().hasHeightForWidth())
        self.shape23_Btn.setSizePolicy(sizePolicy)
        self.shape23_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape23_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape23_Btn.setText("")
        self.shape23_Btn.setCheckable(True)
        self.shape23_Btn.setAutoExclusive(True)
        self.shape23_Btn.setObjectName("shape23_Btn")
        self.shape23_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape23.png')))
        self.shape23_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape23_Btn, 3, 3, 1, 1)
        self.shape40_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape40_Btn.sizePolicy().hasHeightForWidth())
        self.shape40_Btn.setSizePolicy(sizePolicy)
        self.shape40_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape40_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape40_Btn.setText("")
        self.shape40_Btn.setCheckable(True)
        self.shape40_Btn.setAutoExclusive(True)
        self.shape40_Btn.setObjectName("shape40_Btn")
        self.shape40_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape40.png')))
        self.shape40_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape40_Btn, 6, 2, 1, 1)
        self.shape34_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape34_Btn.sizePolicy().hasHeightForWidth())
        self.shape34_Btn.setSizePolicy(sizePolicy)
        self.shape34_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape34_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape34_Btn.setText("")
        self.shape34_Btn.setCheckable(True)
        self.shape34_Btn.setAutoExclusive(True)
        self.shape34_Btn.setObjectName("shape34_Btn")
        self.shape34_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape34.png')))
        self.shape34_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape34_Btn, 5, 2, 1, 1)
        self.shape27_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape27_Btn.sizePolicy().hasHeightForWidth())
        self.shape27_Btn.setSizePolicy(sizePolicy)
        self.shape27_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape27_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape27_Btn.setText("")
        self.shape27_Btn.setCheckable(True)
        self.shape27_Btn.setAutoExclusive(True)
        self.shape27_Btn.setObjectName("shape27_Btn")
        self.shape27_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape27.png')))
        self.shape27_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape27_Btn, 4, 1, 1, 1)
        self.shape33_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape33_Btn.sizePolicy().hasHeightForWidth())
        self.shape33_Btn.setSizePolicy(sizePolicy)
        self.shape33_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape33_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape33_Btn.setText("")
        self.shape33_Btn.setCheckable(True)
        self.shape33_Btn.setAutoExclusive(True)
        self.shape33_Btn.setObjectName("shape33_Btn")
        self.shape33_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape33.png')))
        self.shape33_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape33_Btn, 5, 1, 1, 1)
        self.shape22_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape22_Btn.sizePolicy().hasHeightForWidth())
        self.shape22_Btn.setSizePolicy(sizePolicy)
        self.shape22_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape22_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape22_Btn.setText("")
        self.shape22_Btn.setCheckable(True)
        self.shape22_Btn.setAutoExclusive(True)
        self.shape22_Btn.setObjectName("shape22_Btn")
        self.shape22_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape22.png')))
        self.shape22_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape22_Btn, 3, 2, 1, 1)
        self.shape13_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape13_Btn.sizePolicy().hasHeightForWidth())
        self.shape13_Btn.setSizePolicy(sizePolicy)
        self.shape13_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape13_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape13_Btn.setText("")
        self.shape13_Btn.setCheckable(True)
        self.shape13_Btn.setAutoExclusive(True)
        self.shape13_Btn.setObjectName("shape13_Btn")
        self.shape13_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape13.png')))
        self.shape13_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape13_Btn, 1, 5, 1, 1)
        self.shape11_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape11_Btn.sizePolicy().hasHeightForWidth())
        self.shape11_Btn.setSizePolicy(sizePolicy)
        self.shape11_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape11_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape11_Btn.setText("")
        self.shape11_Btn.setCheckable(True)
        self.shape11_Btn.setAutoExclusive(True)
        self.shape11_Btn.setObjectName("shape11_Btn")
        self.shape11_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape11.png')))
        self.shape11_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape11_Btn, 1, 4, 1, 1)
        self.shape19_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape19_Btn.sizePolicy().hasHeightForWidth())
        self.shape19_Btn.setSizePolicy(sizePolicy)
        self.shape19_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape19_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape19_Btn.setText("")
        self.shape19_Btn.setCheckable(True)
        self.shape19_Btn.setAutoExclusive(True)
        self.shape19_Btn.setObjectName("shape19_Btn")
        self.shape19_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape19.png')))
        self.shape19_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape19_Btn, 2, 5, 1, 1)
        self.shape28_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape28_Btn.sizePolicy().hasHeightForWidth())
        self.shape28_Btn.setSizePolicy(sizePolicy)
        self.shape28_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape28_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape28_Btn.setText("")
        self.shape28_Btn.setCheckable(True)
        self.shape28_Btn.setAutoExclusive(True)
        self.shape28_Btn.setObjectName("shape28_Btn")
        self.shape28_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape28.png')))
        self.shape28_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape28_Btn, 4, 2, 1, 1)
        self.shape10_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape10_Btn.sizePolicy().hasHeightForWidth())
        self.shape10_Btn.setSizePolicy(sizePolicy)
        self.shape10_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape10_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape10_Btn.setText("")
        self.shape10_Btn.setCheckable(True)
        self.shape10_Btn.setAutoExclusive(True)
        self.shape10_Btn.setObjectName("shape10_Btn")
        self.shape10_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape10.png')))
        self.shape10_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape10_Btn, 1, 3, 1, 1)
        self.shape17_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape17_Btn.sizePolicy().hasHeightForWidth())
        self.shape17_Btn.setSizePolicy(sizePolicy)
        self.shape17_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape17_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape17_Btn.setText("")
        self.shape17_Btn.setCheckable(True)
        self.shape17_Btn.setAutoExclusive(True)
        self.shape17_Btn.setObjectName("shape17_Btn")
        self.shape17_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape17.png')))
        self.shape17_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape17_Btn, 2, 3, 1, 1)
        self.shape21_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape21_Btn.sizePolicy().hasHeightForWidth())
        self.shape21_Btn.setSizePolicy(sizePolicy)
        self.shape21_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape21_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape21_Btn.setText("")
        self.shape21_Btn.setCheckable(True)
        self.shape21_Btn.setAutoExclusive(True)
        self.shape21_Btn.setObjectName("shape21_Btn")
        self.shape21_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape21.png')))
        self.shape21_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape21_Btn, 3, 1, 1, 1)
        self.shape31_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape31_Btn.sizePolicy().hasHeightForWidth())
        self.shape31_Btn.setSizePolicy(sizePolicy)
        self.shape31_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape31_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape31_Btn.setText("")
        self.shape31_Btn.setCheckable(True)
        self.shape31_Btn.setAutoExclusive(True)
        self.shape31_Btn.setObjectName("shape31_Btn")
        self.shape31_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape31.png')))
        self.shape31_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape31_Btn, 4, 5, 1, 1)
        self.shape37_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape37_Btn.sizePolicy().hasHeightForWidth())
        self.shape37_Btn.setSizePolicy(sizePolicy)
        self.shape37_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape37_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape37_Btn.setText("")
        self.shape37_Btn.setCheckable(True)
        self.shape37_Btn.setAutoExclusive(True)
        self.shape37_Btn.setObjectName("shape37_Btn")
        self.shape37_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape37.png')))
        self.shape37_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape37_Btn, 5, 5, 1, 1)
        self.shape43_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape43_Btn.sizePolicy().hasHeightForWidth())
        self.shape43_Btn.setSizePolicy(sizePolicy)
        self.shape43_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape43_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape43_Btn.setText("")
        self.shape43_Btn.setCheckable(True)
        self.shape43_Btn.setAutoExclusive(True)
        self.shape43_Btn.setObjectName("shape43_Btn")
        self.shape43_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape43.png')))
        self.shape43_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape43_Btn, 6, 5, 1, 1)
        self.shape18_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape18_Btn.sizePolicy().hasHeightForWidth())
        self.shape18_Btn.setSizePolicy(sizePolicy)
        self.shape18_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape18_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape18_Btn.setText("")
        self.shape18_Btn.setCheckable(True)
        self.shape18_Btn.setAutoExclusive(True)
        self.shape18_Btn.setObjectName("shape18_Btn")
        self.shape18_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape18.png')))
        self.shape18_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape18_Btn, 2, 4, 1, 1)
        self.shape09_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape09_Btn.sizePolicy().hasHeightForWidth())
        self.shape09_Btn.setSizePolicy(sizePolicy)
        self.shape09_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape09_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape09_Btn.setText("")
        self.shape09_Btn.setCheckable(True)
        self.shape09_Btn.setAutoExclusive(True)
        self.shape09_Btn.setObjectName("shape09_Btn")
        self.shape09_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape09.png')))
        self.shape09_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape09_Btn, 1, 2, 1, 1)
        self.shape08_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape08_Btn.sizePolicy().hasHeightForWidth())
        self.shape08_Btn.setSizePolicy(sizePolicy)
        self.shape08_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape08_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape08_Btn.setText("")
        self.shape08_Btn.setCheckable(True)
        self.shape08_Btn.setAutoExclusive(True)
        self.shape08_Btn.setObjectName("shape08_Btn")
        self.shape08_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape08.png')))
        self.shape08_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape08_Btn, 1, 1, 1, 1)
        self.shape38_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape38_Btn.sizePolicy().hasHeightForWidth())
        self.shape38_Btn.setSizePolicy(sizePolicy)
        self.shape38_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape38_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape38_Btn.setText("")
        self.shape38_Btn.setCheckable(True)
        self.shape38_Btn.setAutoExclusive(True)
        self.shape38_Btn.setObjectName("shape38_Btn")
        self.shape38_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape38.png')))
        self.shape38_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape38_Btn, 6, 0, 1, 1)
        self.shape26_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape26_Btn.sizePolicy().hasHeightForWidth())
        self.shape26_Btn.setSizePolicy(sizePolicy)
        self.shape26_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape26_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape26_Btn.setText("")
        self.shape26_Btn.setCheckable(True)
        self.shape26_Btn.setAutoExclusive(True)
        self.shape26_Btn.setObjectName("shape26_Btn")
        self.shape26_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape26.png')))
        self.shape26_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape26_Btn, 4, 0, 1, 1)
        self.shape07_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape07_Btn.sizePolicy().hasHeightForWidth())
        self.shape07_Btn.setSizePolicy(sizePolicy)
        self.shape07_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape07_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape07_Btn.setText("")
        self.shape07_Btn.setCheckable(True)
        self.shape07_Btn.setAutoExclusive(True)
        self.shape07_Btn.setObjectName("shape07_Btn")
        self.shape07_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape07.png')))
        self.shape07_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape07_Btn, 1, 0, 1, 1)
        self.shape14_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape14_Btn.sizePolicy().hasHeightForWidth())
        self.shape14_Btn.setSizePolicy(sizePolicy)
        self.shape14_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape14_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape14_Btn.setText("")
        self.shape14_Btn.setCheckable(True)
        self.shape14_Btn.setAutoExclusive(True)
        self.shape14_Btn.setObjectName("shape14_Btn")
        self.shape14_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape14.png')))
        self.shape14_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape14_Btn, 2, 0, 1, 1)
        self.shape05_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape05_Btn.sizePolicy().hasHeightForWidth())
        self.shape05_Btn.setSizePolicy(sizePolicy)
        self.shape05_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape05_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape05_Btn.setText("")
        self.shape05_Btn.setCheckable(True)
        self.shape05_Btn.setAutoExclusive(True)
        self.shape05_Btn.setObjectName("shape05_Btn")
        self.shape05_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape05.png')))
        self.shape05_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape05_Btn, 0, 4, 1, 1)
        self.shape04_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape04_Btn.sizePolicy().hasHeightForWidth())
        self.shape04_Btn.setSizePolicy(sizePolicy)
        self.shape04_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape04_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape04_Btn.setText("")
        self.shape04_Btn.setCheckable(True)
        self.shape04_Btn.setAutoExclusive(True)
        self.shape04_Btn.setObjectName("shape04_Btn")
        self.shape04_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape04.png')))
        self.shape04_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape04_Btn, 0, 3, 1, 1)
        self.shape03_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape03_Btn.sizePolicy().hasHeightForWidth())
        self.shape03_Btn.setSizePolicy(sizePolicy)
        self.shape03_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape03_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape03_Btn.setText("")
        self.shape03_Btn.setCheckable(True)
        self.shape03_Btn.setAutoExclusive(True)
        self.shape03_Btn.setObjectName("shape03_Btn")
        self.shape03_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape03.png')))
        self.shape03_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape03_Btn, 0, 2, 1, 1)
        self.shape06_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape06_Btn.sizePolicy().hasHeightForWidth())
        self.shape06_Btn.setSizePolicy(sizePolicy)
        self.shape06_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape06_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape06_Btn.setText("")
        self.shape06_Btn.setCheckable(True)
        self.shape06_Btn.setAutoExclusive(True)
        self.shape06_Btn.setObjectName("shape06_Btn")
        self.shape06_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape06.png')))
        self.shape06_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape06_Btn, 0, 5, 1, 1)
        self.shape01_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape01_Btn.sizePolicy().hasHeightForWidth())
        self.shape01_Btn.setSizePolicy(sizePolicy)
        self.shape01_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape01_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape01_Btn.setText("")
        self.shape01_Btn.setCheckable(True)
        self.shape01_Btn.setChecked(True)
        self.shape01_Btn.setAutoExclusive(True)
        self.shape01_Btn.setObjectName("shape01_Btn")
        self.shape01_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape01.png')))
        self.shape01_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape01_Btn, 0, 0, 1, 1)
        self.shape20_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape20_Btn.sizePolicy().hasHeightForWidth())
        self.shape20_Btn.setSizePolicy(sizePolicy)
        self.shape20_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape20_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape20_Btn.setText("")
        self.shape20_Btn.setCheckable(True)
        self.shape20_Btn.setAutoExclusive(True)
        self.shape20_Btn.setObjectName("shape20_Btn")
        self.shape20_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape20.png')))
        self.shape20_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape20_Btn, 3, 0, 1, 1)
        self.shape02_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape02_Btn.sizePolicy().hasHeightForWidth())
        self.shape02_Btn.setSizePolicy(sizePolicy)
        self.shape02_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape02_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape02_Btn.setText("")
        self.shape02_Btn.setCheckable(True)
        self.shape02_Btn.setAutoExclusive(True)
        self.shape02_Btn.setObjectName("shape02_Btn")
        self.shape02_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape02.png')))
        self.shape02_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape02_Btn, 0, 1, 1, 1)
        self.shape32_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape32_Btn.sizePolicy().hasHeightForWidth())
        self.shape32_Btn.setSizePolicy(sizePolicy)
        self.shape32_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape32_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape32_Btn.setText("")
        self.shape32_Btn.setCheckable(True)
        self.shape32_Btn.setAutoExclusive(True)
        self.shape32_Btn.setObjectName("shape32_Btn")
        self.shape32_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape32.png')))
        self.shape32_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape32_Btn, 5, 0, 1, 1)
        self.shape16_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape16_Btn.sizePolicy().hasHeightForWidth())
        self.shape16_Btn.setSizePolicy(sizePolicy)
        self.shape16_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape16_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape16_Btn.setText("")
        self.shape16_Btn.setCheckable(True)
        self.shape16_Btn.setAutoExclusive(True)
        self.shape16_Btn.setObjectName("shape16_Btn")
        self.shape16_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape16.png')))
        self.shape16_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape16_Btn, 2, 2, 1, 1)
        self.shape15_Btn = QtWidgets.QPushButton(self.topScrGrid_Lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape15_Btn.sizePolicy().hasHeightForWidth())
        self.shape15_Btn.setSizePolicy(sizePolicy)
        self.shape15_Btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shape15_Btn.setMaximumSize(QtCore.QSize(40, 50))
        self.shape15_Btn.setText("")
        self.shape15_Btn.setCheckable(True)
        self.shape15_Btn.setAutoExclusive(True)
        self.shape15_Btn.setObjectName("shape15_Btn")
        self.shape15_Btn.setIcon(QtGui.QIcon(str(iconDir+'Shape15.png')))
        self.shape15_Btn.setIconSize(QtCore.QSize(40,40))
        self.gridLayout_3.addWidget(self.shape15_Btn, 2, 1, 1, 1)
        self.top_Scrl.setWidget(self.topScrGrid_Lay)
        self.gridLayout_2.addWidget(self.top_Scrl, 0, 0, 1, 1)
        self.topVert_Lay.addWidget(self.shapes_Grp)
        self.gridLayout_6.addLayout(self.topVert_Lay, 0, 0, 1, 2)
        self.pivot_Btn = QtWidgets.QPushButton(MainWindow)
        self.pivot_Btn.setObjectName("pivot_Btn")
        self.gridLayout_6.addWidget(self.pivot_Btn, 7, 0, 1, 1)
        self.line02_Line = QtWidgets.QFrame(MainWindow)
        self.line02_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line02_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line02_Line.setObjectName("line02_Line")
        self.gridLayout_6.addWidget(self.line02_Line, 2, 0, 1, 2)
        self.combine_Btn = QtWidgets.QPushButton(MainWindow)
        self.combine_Btn.setObjectName("combine_Btn")
        self.gridLayout_6.addWidget(self.combine_Btn, 8, 0, 1, 1)
        self.double_Btn = QtWidgets.QPushButton(MainWindow)
        self.double_Btn.setObjectName("double_Btn")
        self.gridLayout_6.addWidget(self.double_Btn, 8, 1, 1, 1)

        self.retranslateUi(MainWindow)
        self.locNum_Cmb.setCurrentIndex(1)
        self.grpNum_Cmb.setCurrentIndex(1)
        QtCore.QObject.connect(self.name_Ledit, QtCore.SIGNAL("returnPressed()"), self.create_Btn.animateClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Matriarch Control Manager", None, -1))
        self.mirror_Grp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Mirror", None, -1))
        self.x_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.y_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.z_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.freeze_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Freeze", None, -1))
        self.colour_Grp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Colour", None, -1))
        self.default_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Default", None, -1))
        self.override_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Override", None, -1))
        self.name_Lab.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.locNum_Cmb.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.locNum_Cmb.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.locNum_Cmb.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.locNum_Cmb.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.locNum_Cmb.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.locNum_Cmb.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.locNum_Cmb.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.locNum_Cmb.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.locNum_Cmb.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.locNum_Cmb.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.locators_Lab.setText(QtWidgets.QApplication.translate("MainWindow", "Locators", None, -1))
        self.grpNum_Cmb.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.grpNum_Cmb.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.grpNum_Cmb.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.grpNum_Cmb.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.grpNum_Cmb.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.grpNum_Cmb.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.grpNum_Cmb.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.grpNum_Cmb.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.grpNum_Cmb.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.grpNum_Cmb.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.groups_Lab.setText(QtWidgets.QApplication.translate("MainWindow", "Groups", None, -1))
        self.create_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.shapes_Grp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Shapes", None, -1))
        self.pivot_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Center Pivot", None, -1))
        self.combine_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Combine", None, -1))
        self.double_Btn.setText(QtWidgets.QApplication.translate("MainWindow", "Double Up", None, -1))

