# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/Jenks/maya/scripts/Jenks/scripts/jointDuplicator/jointDuplicatorUI.ui'
#
# Created: Wed Sep 21 14:38:13 2016
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 340)
        MainWindow.setMinimumSize(QtCore.QSize(300, 340))
        MainWindow.setMaximumSize(QtCore.QSize(300, 340))
        self.gridLayout_3 = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 2, 1, 1)
        self.suffixGroup = QtWidgets.QGroupBox(MainWindow)
        self.suffixGroup.setObjectName("suffixGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.suffixGroup)
        self.gridLayout_2.setContentsMargins(40, -1, 10, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainSuffixLabel = QtWidgets.QLabel(self.suffixGroup)
        self.mainSuffixLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mainSuffixLabel.setObjectName("mainSuffixLabel")
        self.gridLayout_2.addWidget(self.mainSuffixLabel, 0, 0, 1, 1)
        self.curSuffixBox = QtWidgets.QLineEdit(self.suffixGroup)
        self.curSuffixBox.setObjectName("curSuffixBox")
        self.gridLayout_2.addWidget(self.curSuffixBox, 0, 1, 1, 1)
        self.suffixALabel = QtWidgets.QLabel(self.suffixGroup)
        self.suffixALabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.suffixALabel.setObjectName("suffixALabel")
        self.gridLayout_2.addWidget(self.suffixALabel, 1, 0, 1, 1)
        self.suffixABox = QtWidgets.QLineEdit(self.suffixGroup)
        self.suffixABox.setObjectName("suffixABox")
        self.gridLayout_2.addWidget(self.suffixABox, 1, 1, 1, 1)
        self.suffixBLabel = QtWidgets.QLabel(self.suffixGroup)
        self.suffixBLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.suffixBLabel.setObjectName("suffixBLabel")
        self.gridLayout_2.addWidget(self.suffixBLabel, 2, 0, 1, 1)
        self.suffixBBox = QtWidgets.QLineEdit(self.suffixGroup)
        self.suffixBBox.setObjectName("suffixBBox")
        self.gridLayout_2.addWidget(self.suffixBBox, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.suffixGroup, 1, 0, 1, 3)
        self.modeGroup = QtWidgets.QGroupBox(MainWindow)
        self.modeGroup.setEnabled(True)
        self.modeGroup.setMaximumSize(QtCore.QSize(16777215, 40))
        self.modeGroup.setFlat(False)
        self.modeGroup.setCheckable(False)
        self.modeGroup.setObjectName("modeGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.modeGroup)
        self.gridLayout.setContentsMargins(-1, 0, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.modeSelRad = QtWidgets.QRadioButton(self.modeGroup)
        self.modeSelRad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.modeSelRad.setChecked(True)
        self.modeSelRad.setObjectName("modeSelRad")
        self.gridLayout.addWidget(self.modeSelRad, 0, 0, 1, 1)
        self.modeHeirRad = QtWidgets.QRadioButton(self.modeGroup)
        self.modeHeirRad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.modeHeirRad.setObjectName("modeHeirRad")
        self.gridLayout.addWidget(self.modeHeirRad, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.modeGroup, 0, 0, 1, 3)
        self.createBtn = QtWidgets.QPushButton(MainWindow)
        self.createBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.createBtn.setObjectName("createBtn")
        self.gridLayout_3.addWidget(self.createBtn, 3, 1, 1, 1)
        self.controlGroup = QtWidgets.QGroupBox(MainWindow)
        self.controlGroup.setObjectName("controlGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.controlGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.setCtrlCrvBtn = QtWidgets.QPushButton(self.controlGroup)
        self.setCtrlCrvBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.setCtrlCrvBtn.setObjectName("setCtrlCrvBtn")
        self.gridLayout_4.addWidget(self.setCtrlCrvBtn, 0, 0, 1, 1)
        self.attrNameBox = QtWidgets.QLineEdit(self.controlGroup)
        self.attrNameBox.setObjectName("attrNameBox")
        self.gridLayout_4.addWidget(self.attrNameBox, 1, 2, 1, 1)
        self.ctrlCrvBox = QtWidgets.QLineEdit(self.controlGroup)
        self.ctrlCrvBox.setObjectName("ctrlCrvBox")
        self.gridLayout_4.addWidget(self.ctrlCrvBox, 0, 1, 1, 2)
        self.attrLabel = QtWidgets.QLabel(self.controlGroup)
        self.attrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.attrLabel.setObjectName("attrLabel")
        self.gridLayout_4.addWidget(self.attrLabel, 1, 0, 1, 2)
        self.attrNiceLabel = QtWidgets.QLabel(self.controlGroup)
        self.attrNiceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.attrNiceLabel.setObjectName("attrNiceLabel")
        self.gridLayout_4.addWidget(self.attrNiceLabel, 2, 0, 1, 2)
        self.attrNiceNameBox = QtWidgets.QLineEdit(self.controlGroup)
        self.attrNiceNameBox.setObjectName("attrNiceNameBox")
        self.gridLayout_4.addWidget(self.attrNiceNameBox, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.controlGroup, 2, 0, 1, 3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Joint Duplicator", None, -1))
        self.suffixGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "Suffixes", None, -1))
        self.mainSuffixLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Main Suffix", None, -1))
        self.curSuffixBox.setText(QtWidgets.QApplication.translate("MainWindow", "result", None, -1))
        self.suffixALabel.setText(QtWidgets.QApplication.translate("MainWindow", "Suffix A", None, -1))
        self.suffixABox.setText(QtWidgets.QApplication.translate("MainWindow", "IK", None, -1))
        self.suffixBLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Suffix B", None, -1))
        self.suffixBBox.setText(QtWidgets.QApplication.translate("MainWindow", "FK", None, -1))
        self.modeGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "Mode", None, -1))
        self.modeSelRad.setText(QtWidgets.QApplication.translate("MainWindow", "Selected Joints", None, -1))
        self.modeHeirRad.setText(QtWidgets.QApplication.translate("MainWindow", "Joint Heirachy", None, -1))
        self.createBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.controlGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "Control", None, -1))
        self.setCtrlCrvBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.attrNameBox.setText(QtWidgets.QApplication.translate("MainWindow", "IKFKSwitch", None, -1))
        self.ctrlCrvBox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Control Name", None, -1))
        self.attrLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Attribute Name", None, -1))
        self.attrNiceLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Nice Name", None, -1))
        self.attrNiceNameBox.setText(QtWidgets.QApplication.translate("MainWindow", "IK / FK Switch", None, -1))

